# permissions for end users to view quotes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: quotes-viewer-role
rules:
- apiGroups:
  - examples.example.com
  resources:
  - quotes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - examples.example.com
  resources:
  - quotes/status
  verbs:
  - get
